### ISSUE TITLE
Failing tests on Ruby 3.0

### ISSUE THREAD

**Issue by junaruga** [steveklabnik/mono_logger#7]
I see the following failing tests on Ruby 3.0. The mono_logger is a runtime dependency of [reque](https://rubygems.org/gems/resque). That's why I am trying to pass the tests. Could you @steveklabnik take a look at the code? Could you consider adding Ruby 3.0 to Travis CI or alternative CI such as GitHub Actions, as nowadays Travis might be slow. Thanks.

```
$ cat /etc/fedora-release 
Fedora release 33 (Thirty Three)

$ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

$ bundle -v
Bundler version 2.2.3
```

Remove the following "bundler" line to work with the bundler 2.2.3 above.

```
diff --git a/mono_logger.gemspec b/mono_logger.gemspec
index 9778058..4fe256f 100644
--- a/mono_logger.gemspec
+++ b/mono_logger.gemspec
@@ -19,7 +19,6 @@ Gem::Specification.new do |spec|
   spec.test_files    = spec.files.grep(%r{^(test|spec|features)/})
   spec.require_paths = ["lib"]
 
-  spec.add_development_dependency "bundler", "~> 1.3"
   spec.add_development_dependency "rake"
   spec.add_development_dependency "minitest", "~> 5.0"
 end
```

```
$ bundle install --path vendor/bundle

$ bundle exec rake test

/usr/local/ruby-3.0.0/bin/ruby -w -I"lib:lib" -w /home/jaruga/git/mono_logger/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/rake_test_loader.rb "test/mri_logger_test.rb" 
/home/jaruga/git/mono_logger/test/mri_logger_test.rb:263: warning: assigned but unused variable - read_ready
/home/jaruga/git/mono_logger/test/mri_logger_test.rb:343: warning: assigned but unused variable - read_ready
/home/jaruga/git/mono_logger/test/mri_logger_test.rb:367: warning: assigned but unused variable - read_ready
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
/home/jaruga/git/mono_logger/test/mri_logger_test.rb:23: warning: already initialized constant Logger
/usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/version.rb:3: warning: previous definition of Logger was here
Run options: --seed 34714

# Running:

SSEEDEPRECATED: `rubinius?` called from /home/jaruga/git/mono_logger/test/mri_logger_test.rb:339. This will fail in Minitest 6.
ESEEE/usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/formatter.rb:22: warning: strftime called with empty format string
...........

Finished in 0.006788s, 2946.3851 runs/s, 13995.3290 assertions/s.

  1) Error:
TestLogDevice#test_initialize:
ArgumentError: wrong number of arguments (given 2, expected 0..1)
    /usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/log_device.rb:14:in `initialize'
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:306:in `new'
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:306:in `d'
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:310:in `test_initialize'

  2) Error:
TestLogDevice#test_close:
ArgumentError: wrong number of arguments (given 2, expected 0..1)
    /usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/log_device.rb:14:in `initialize'
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:306:in `new'
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:306:in `d'
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:365:in `test_close'

  3) Error:
TestLogDevice#test_write:
ArgumentError: wrong number of arguments (given 2, expected 0..1)
    /usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/log_device.rb:14:in `initialize'
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:306:in `new'
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:306:in `d'
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:341:in `test_write'

  4) Error:
TestLoggerApplication#test_logger:
NameError: uninitialized constant MonoLogger::Application
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:502:in `setup'

Error:
TestLoggerApplication#test_logger:
NoMethodError: undefined method `close' for nil:NilClass
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:510:in `teardown'

  5) Error:
TestLoggerApplication#test_start:
NameError: uninitialized constant MonoLogger::Application
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:502:in `setup'

Error:
TestLoggerApplication#test_start:
NoMethodError: undefined method `close' for nil:NilClass
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:510:in `teardown'

  6) Error:
TestLoggerApplication#test_initialize:
NameError: uninitialized constant MonoLogger::Application
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:502:in `setup'

Error:
TestLoggerApplication#test_initialize:
NoMethodError: undefined method `close' for nil:NilClass
    /home/jaruga/git/mono_logger/test/mri_logger_test.rb:510:in `teardown'

20 runs, 95 assertions, 0 failures, 6 errors, 3 skips

You have skipped tests. Run with --verbose for details.
[Coveralls] Outside the CI environment, not sending data.
rake aborted!
Command failed with status (1): [ruby -w -I"lib:lib" -w /home/jaruga/git/mono_logger/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/rake_test_loader.rb "test/mri_logger_test.rb" ]
/home/jaruga/git/mono_logger/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/ruby-3.0.0/bin/bundle:23:in `load'
/usr/local/ruby-3.0.0/bin/bundle:23:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by junaruga** [comment]
We can fix the failure 4), 5), 6) by applying the PR https://github.com/steveklabnik/mono_logger/pull/6 .

**Comment by junaruga** [comment]
The error 1), 2), 3) happen on the following line on Ruby 3.0. This error does not happen on Ruby 2.7.

```
  def d(log, opt = {}) 
    Logger::LogDevice.new(log, opt) # <= This one!
  end
```

https://ruby-doc.org/stdlib-3.0.0/libdoc/logger/rdoc/Logger/LogDevice.html#method-c-new
https://ruby-doc.org/stdlib-2.7.2/libdoc/logger/rdoc/Logger/LogDevice.html#method-c-new

```
new(log = nil, shift_age: nil, shift_size: nil, shift_period_suffix: nil, binmode: false)
```

I think this is an issue about the new keyword arguments.
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

**Comment by junaruga** [comment]
I sent the PR #8 to fix this issue.
