### ISSUE TITLE
Warnings in the tests.

### ISSUE THREAD

**Issue by junaruga** [steveklabnik/mono_logger#9]
The tests by the `bundle exec rake` with my local Ruby 3.0 and the GitHub Actions show the following warnings.
I thinks this is something we can fix.

```
/home/jaruga/git/mono_logger/test/mri_logger_test.rb:265: warning: assigned but unused variable - read_ready
/home/jaruga/git/mono_logger/test/mri_logger_test.rb:345: warning: assigned but unused variable - read_ready
/home/jaruga/git/mono_logger/test/mri_logger_test.rb:369: warning: assigned but unused variable - read_ready
/home/jaruga/git/mono_logger/test/mri_logger_test.rb:25: warning: already initialized constant Logger
/usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/version.rb:3: warning: previous definition of Logger was here
DEPRECATED: `rubinius?` called from /home/jaruga/git/mono_logger/test/mri_logger_test.rb:341. This will fail in Minitest 6.
/usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/formatter.rb:22: warning: strftime called with empty format string
```

https://github.com/steveklabnik/mono_logger/blob/71fb1f03ebf8b81909dbc8ad64857f9176043f89/test/mri_logger_test.rb#L25

@steveklabnik what's your intent of this line? This line shows the one of the warnings.

```
$ bundle exec irb
irb(main):001:0> Logger
=> Logger
irb(main):002:0> require 'mono_logger'
=> true
irb(main):003:0> Logger = MonoLogger
(irb):3: warning: already initialized constant Logger
/usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/version.rb:3: warning: previous definition of Logger was here
=> MonoLogger
```

**Comment by steveklabnik** [comment]
I wrote this code eight years ago, I don't exactly remember. If I had to guess, this is effectively a monkeypatch of https://ruby-doc.org/stdlib-2.4.0/libdoc/logger/rdoc/Logger.html to use monologger instead. This warning is basically complaining about something that was being done on purpose.

**Comment by junaruga** [comment]
@steveklabnik OK. I can understand it's hard to remember the things eight years ago :)

I sent another PR #10 to fix 2 type of warnings.

The remaining 1 warning happens on `test_datetime_format`.

```
$ bundle exec ruby -w test/mri_logger_test.rb --name test_datetime_format
...
/usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/formatter.rb:22: warning: strftime called with empty format string
...
1 runs, 6 assertions, 0 failures, 0 errors, 0 skips
```

When I add the debugging line `raise` to find the error line and stacktrace, I see `test/mri_logger_test.rb:67` causes the warning. I am not sure why for now.

/usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/formatter.rb:22

```
    def format_datetime(time)
      raise # <= added this line for debug
      time.strftime(@datetime_format || "%Y-%m-%dT%H:%M:%S.%6N ")
    end
```

```
$ bundle exec ruby -w test/mri_logger_test.rb --name test_datetime_format
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
test/mri_logger_test.rb:25: warning: already initialized constant Logger
/usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/version.rb:3: warning: previous definition of Logger was here
Run options: --name test_datetime_format --seed 41725

# Running:

E

Finished in 0.001116s, 896.0654 runs/s, 0.0000 assertions/s.

  1) Error:
TestLogger#test_datetime_format:
RuntimeError: 
    /usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/formatter.rb:22:in `format_datetime'
    /usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger/formatter.rb:15:in `call'
    /usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger.rb:586:in `format_message'
    /usr/local/ruby-3.0.0/lib/ruby/3.0.0/logger.rb:476:in `add'
    test/mri_logger_test.rb:67:in `log_raw'
    test/mri_logger_test.rb:61:in `log'
    test/mri_logger_test.rb:57:in `log_add'
    test/mri_logger_test.rb:117:in `test_datetime_format'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
[Coveralls] Outside the CI environment, not sending data.
```

**Comment by junaruga** [comment]
For the above warning, I suppose that maybe the way to create `Logger` instance was changed, and setting the `logger.datetime_format` is required around the `log_raw` method. But I am not sure.

https://ruby-doc.org/stdlib-3.0.0/libdoc/logger/rdoc/Logger.html
https://github.com/ruby/ruby/blob/v3_0_0/lib/logger.rb

**Comment by junaruga** [comment]
I find this warning in the tests on Ruby 2.0.0 and Ruby 2.1. So, I think it's no problem to release it. Of course it's nice to fix it.

https://travis-ci.org/github/steveklabnik/mono_logger/jobs/763010326#L269
https://github.com/steveklabnik/mono_logger/runs/2115229878?check_suite_focus=true#step:6:13

**Comment by steveklabnik** [comment]
I have published 1.1.1. Thanks again, sorry this took so long.

**Comment by sambostock** [comment]
@junaruga, @steveklabnik is this issue safe to close now?
